### PR TITLE
Add initial gamma truth info

### PR DESCRIPTION
**Pull request by pdeperio**
Replace ```dummy neutrino``` in NUANCE input file to the actual initial gamma kinematics.

@nickwp Not sure what's going on with rotations, but I just copy/pasted for the gamma direction vector. Please double check.

### CODE REVIEW

**Comment by nickwp** [comment]
This is a nice way to keep the gamma truth info.
Unfortunately though when WCSim reads in these tracks it does actually simulate even the dummy neutrino track (this dummy neutrino track is required in the input format, but it does simulate the neutrino, of course the neutrino just travels through without doing anything - this seems to be a sort of hack to be able to keep the neutrino truth info in WCSim). So changing it to a gamma track will cause it to simulate the gamma as well as the positron and electron. I suggest we just change the PID back to a neutrino but keep it using the gamma's direction and energy, so that we can access that truth info by looking at the 'dummy neutrino' that has the gamma's kinematics. It's an ugly hack, but without making changes to the WCSim output format to specifically add something for the gamma (which will cause problems reading the output files unless that new info is always there, even when it's not a gamma simulation) I don't know any other way we can keep the initial gamma truth info.
Could you change the PID of the dummy gamma back to a neutrino PID? (I'd do myself but not sure how to commit to your fork / pull request, if that's even possible)

**Comment by pdeperio** [comment]
just click the ```dump_gamma_truth``` branch link above, then browse to the file and edit and commit

**Comment by nickwp** [comment]
Hmm, sorry, it looks like I was actually wrong about what I said before... It certainly used to be the case (you could see the neutrino track in the visualisation) but must have changed at some point. Or possibly I'm remembering some simulations where the input format where for some reason the neutrino had the flag 0 at the end instead of -1 at the end (only tracks with 0 are simulated). Anyway, checking the WCSim code itself, it does nothing at all with that line. So this change will affect the txt file produced for input to WCSim, but will not change the final WCSim output in any way.

**Comment by nickwp** [comment]
In this case, I guess it does what you intended? Unless you wanted the gamma truth to be in the final WCSim output?

**Comment by pdeperio** [comment]
ya, i think we should propagate the truth all the way forward, so it's available for analysts (e.g. plotting efficiencies as a function of gamma energy)

**Comment by nickwp** [comment]
To propagate all the way through, I'm not sure how best to do this. We'd need to change WCSim itself to add somewhere to include it, I think. Maybe we can add an extra track which contains the gamma kinematics and has the PID of a "geantino" (a fake particle that just passes through and does not interact)

**Comment by pdeperio** [comment]
How does the neutrino info get passed through usually for e.g. NuPRISM analyses?

**Comment by nickwp** [comment]
If you use this nuance input format, it doesn't get passed through at all (see lines 130 to 239 of https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimPrimaryGeneratorAction.cc it gets saved into variables that are never used).
If you use the nRooTracker format instead, the entire tree of the NEUT output root file gets copied across to the WCSim output file.

**Comment by nickwp** [comment]
Delving deeper, it seems these variables are actually used but in a different class in a different file so I didn't spot it... At the end of the event, when filling the WCSimRootEvent, two additional tracks are added which correspond to the neutrino and the target, so actually I think we're good, it will be saved as additional tracks which we can identify in the WCSim output. This could then be added to the npz files but should discuss with Wojtek how to do that, because we I don't think we want a different format for the gamma events than for the other events. For now I suppose having the original gamma truth info only in the WCSim output will be enough.

**Comment by pdeperio** [comment]
from [this line in ```event_dump.py```](https://github.com/WatChMaL/DataTools/blob/master/root_utils/event_dump.py#L49), it looks like the new gamma will be saved in the output ```.npz```. @wfedorko will this be a problem for downstream analysis?

**Comment by nickwp** [comment]
I think it won't save it, because it only saves particles that have flag of 0 ([this line in `root_file_utils.py`](https://github.com/WatChMaL/DataTools/blob/master/root_utils/root_file_utils.py#L59)). This track will have flag of -1 which is usually used to indicate the initial neutrino.

**Comment by pdeperio** [comment]
ah ok, how about this hack above ^?

**Comment by nickwp** [comment]
I think we don't want to save the gamma like that, because it will break several other scripts that won't correctly handle the extra gamma being included. So it was good before?
In any case, the npz format will need changing quite a bit, because we need to include end caps and format it to be able to work with various architectures (point cloud, graph, sparse submanifold) then conversion from npz to h5 can be specific for each architecture's needs.
For now maybe we should revert that change to the `root_file_utils.py` so as not to break anything, but accept the change to `DumpGammaConvProducts.C` change so the WCSim output has the gamma truth and can be used in later versions of the npz conversion etc?

**Comment by nickwp** [comment]
I've gone ahead and merged this now, so that future production runs can use the gamma truth directly

**Pull request merged**
